### ISSUE TITLE
.Net Core Support

### ISSUE THREAD

**Issue by Omzig** [vigneshmsft/Spry#3]
When loading into a .net Core lib, the reverences complains that it is a regular .net library. Please add .net core support.

**Comment by vigneshmsft** [comment]
Thanks for raising this issue, I update the code base to .NET Standard to support using in .NET Core and .NET 472 projects, but was lazy to setup the Azure DevOps pipeline, I have done that now.
Version [1.0.5 of Spry](https://www.nuget.org/packages/Spry/1.0.5) is now published to nuget
